services:
  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - postgres_prod:/var/lib/postgresql/data

  frontend:
    image: next2:latest  # Использование образа, переданного на сервер
    ports:
      - "8080:80"
    volumes:
      - /app/node_modules

  backend:
    image: strapi:latest  # Использование образа, переданного на сервер
    ports:
      - "1337:1337"
    volumes:
      - /app/node_modules
      - strapi_public_prod:/app/public
    depends_on:
      - postgres

volumes:
  postgres_prod:
  strapi_public_prod:
