services:
  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - postgres_prod:/var/lib/postgresql/data
  frontend:
    build:
      context: /root/next2
      dockerfile: Dockerfile.production
    ports:
      - "80:80"
    volumes:
      - /app/node_modules
  backend:
    build:
      context: /root/website
      dockerfile: Dockerfile.production
    ports:
      - "1337:1337"
    volumes:
      - /app/node_modules
      - strapi_public_prod:/app/public
    depends_on:
      - postgres
volumes:
  postgres_prod:
  strapi_public_prod: