version: '3.7'

services:
  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - postgres_prod:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # Использование переменной окружения

  frontend:
    build:
      context: /root/next2
      dockerfile: Dockerfile.production
    ports:
      - "8080:80"
    volumes:
      - /app/node_modules

  backend:
    build:
      context: /root/website
      dockerfile: Dockerfile.production
    ports:
      - "1337:1337"
    volumes:
      - /app/node_modules
      - strapi_public_prod:/app/public
    depends_on:
      - postgres
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}  # Использование переменной окружения

volumes:
  postgres_prod:
  strapi_public_prod:
