version: '3.7'

services:
  postgres:
    image: "postgres"
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_prod:/var/lib/postgresql/data
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE_SSL: ${DATABASE_SSL}
      NODE_ENV: production

  frontend:
    image: next2:latest
    restart: always
    ports:
      - "8080:80"
    volumes:
      - /root/next2/node_modules:/app/node_modules
    environment:
      NODE_ENV: production

  backend:
    image: strapi:latest
    restart: always
    ports:
      - "1337:1337"
    volumes:
      - /root/website/node_modules:/app/node_modules
      - strapi_public_prod:/app/public
    depends_on:
      - postgres
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE_SSL: ${DATABASE_SSL}
      NODE_ENV: production

volumes:
  postgres_prod:
  strapi_public_prod:
