version: '3.7'

services:
  postgres:
    image: "postgres"
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_prod:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  frontend:
    image: next2:latest
    restart: always
    ports:
      - "8080:80"
    volumes:
      - /root/next2/node_modules:/app/node_modules

  backend:
    image: strapi:latest
    restart: always
    ports:
      - "1337:1337"
    volumes:
      - /root/website/node_modules:/app/node_modules
      - strapi_public_prod:/app/public
    depends_on:
      - postgres
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  postgres_prod:
  strapi_public_prod:
