FROM node:22-alpine

RUN apk add --no-cache python3 make g++

WORKDIR /app

COPY package*.json ./

RUN npm install pg

RUN npm install

COPY . .

RUN npm run build

CMD ["npm", "start"]
