name: Build, Push, Deploy Docker Containers

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image for Next.js
        run: |
          cd next2
          docker build -t next2:latest -f Dockerfile.production .
          docker save next2:latest -o ../next2.tar

      - name: Build Docker image for Strapi
        run: |
          cd website
          docker build -t strapi:latest -f Dockerfile.production .
          docker save strapi:latest -o ../strapi.tar

      - name: Upload Next.js Docker image to GitHub artifacts
        uses: actions/upload-artifact@v4
        with:
          name: next2-image
          path: next2.tar

      - name: Upload Strapi Docker image to GitHub artifacts
        uses: actions/upload-artifact@v4
        with:
          name: strapi-image
          path: strapi.tar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Next.js Docker image from GitHub artifacts
        uses: actions/download-artifact@v4
        with:
          name: next2-image

      - name: Download Strapi Docker image from GitHub artifacts
        uses: actions/download-artifact@v4
        with:
          name: strapi-image

      - name: Set up SSH
        uses: webfactory/ssh-agent@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy Docker images to VPS
        uses: appleboy/scp-action@v0.1.0
        with:
          source: |
            next2.tar
            strapi.tar
          target: /root/
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT }}

      - name: Copy docker-compose-production.yml to VPS
        uses: appleboy/scp-action@v0.1.0
        with:
          source: docker-compose-production.yml
          target: /root/
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT }}

      - name: SSH into VPS and restart containers with new images
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /root/
            docker load -i next2.tar
            docker load -i strapi.tar
            docker-compose down
            docker-compose up -d --build
          debug: true
