name: Build, Push, Deploy Docker Containers

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image for Next.js
        run: |
          cd next2
          docker build -t next2:latest -f Dockerfile.production .
          docker save next2:latest -o next2.tar

      - name: Build Docker image for Strapi
        run: |
          cd website
          docker build -t strapi:latest -f Dockerfile.production .
          docker save strapi:latest -o strapi.tar

      - name: Upload Next.js Docker image to GitHub artifacts
        uses: actions/upload-artifact@v2
        with:
          name: next2-image
          path: next2.tar

      - name: Upload Strapi Docker image to GitHub artifacts
        uses: actions/upload-artifact@v2
        with:
          name: strapi-image
          path: strapi.tar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Next.js Docker image from GitHub artifacts
        uses: actions/download-artifact@v2
        with:
          name: next2-image
          path: .

      - name: Download Strapi Docker image from GitHub artifacts
        uses: actions/download-artifact@v2
        with:
          name: strapi-image
          path: .

      - name: Check if images exist
        run: |
          if [ ! -f "next2.tar" ]; then echo "next2.tar not found!"; exit 1; fi
          if [ ! -f "strapi.tar" ]; then echo "strapi.tar not found!"; exit 1; fi

      - name: Copy Docker images to VPS
        uses: appleboy/scp-action@v0.1.0
        with:
          source: |
            next2.tar
            strapi.tar
          target: /root/docker_images/
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}

      - name: Copy docker-compose-production.yml to VPS
        uses: appleboy/scp-action@v0.1.0
        with:
          source: docker-compose-production.yml
          target: /root/docker_images/
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}

      - name: SSH into VPS and restart containers with new images
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /root/docker_images/
            docker-compose down
            docker-compose up -d --build
          debug: true
