name: Build, Push, Deploy Docker Containers

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Next.js Docker image
        run: |
          cd next2
          docker build -t next2:latest -f Dockerfile.production .
          docker tag next2:latest ${{ secrets.DOCKER_USERNAME }}/next2:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/next2:latest

      - name: Build and push Strapi Docker image
        run: |
          cd website
          docker build -t strapi:latest -f Dockerfile.production .
          docker tag strapi:latest ${{ secrets.DOCKER_USERNAME }}/strapi:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/strapi:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy docker-compose-production.yml to VPS
        uses: appleboy/scp-action@v0.1.0
        with:
          source: docker-compose-production.yml
          target: /root/docker_images/
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT }}

      - name: SSH into VPS and restart containers with new images
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /root/docker_images/
            docker-compose down
            docker-compose pull
            docker-compose up -d
          debug: true
