name: Build, Push, Deploy Docker Containers43

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image for Next.js
        run: |
          cd next2
          docker build -t next2:latest -f Dockerfile.production .
          docker save next2:latest -o ../next2.tar

      - name: Build Docker image for Strapi
        run: |
          cd website
          docker build -t strapi:latest -f Dockerfile.production .
          docker save strapi:latest -o ../strapi.tar

      - name: Загрузка 1 докера GitHub artifacts
        uses: actions/upload-artifact@v4
        with:
          name: next2-image
          path: next2.tar

      - name: Загрузка 2 докера GitHub artifacts
        uses: actions/upload-artifact@v4
        with:
          name: strapi-image
          path: strapi.tar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Скачивание 1 из артефакта
        uses: actions/download-artifact@v4
        with:
          name: next2-image

      - name: Скачивание 2 из артефакта
        uses: actions/download-artifact@v4
        with:
          name: strapi-image

      - name: Проверка что файлы существуют
        run: |
          ls
          pwd
          ls -la next2.tar
          ls -la strapi.tar

      - name: SCP
        uses: appleboy/scp-action@v0.1.0
        with:
          source: |
            next2.tar
            strapi.tar
          target: /
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}  # Здесь передается пароль
          port: ${{ secrets.VPS_PORT }}

      - name: SSH into VPS and restart containers with new images
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}  # Здесь передается пароль
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /root/
            docker load -i next2.tar
            docker load -i strapi.tar
            docker-compose down
            docker-compose up -d --build